#!/bin/sh

usage(){
	echo "usage: git sp [-a] <message>

	Commits and pushes to current branch on origin.
	-a 	Run 'git add -A' prior to committing.
	exit 1
}


# -a should trigger `git add -A`
while getopts 'a' flag; do
	aflag='true'
done

if test "$#" -lt 1 
then
	usage
else
	branch=$(git rev-parse --abbrev-ref HEAD)
	if test $aflag 
	then
		git add -A
		git commit -m "$2"
	else
		git commit -m "$1"
	fi
	git push origin $branch
fi
