#!/bin/sh

while getopts 'a' flag; do
	aflag='true'
done

if test "$#" -lt 1 
then
	echo "Aborting due to empty commit message"
else
	branch=$(git rev-parse --abbrev-ref HEAD)
	if test $aflag 
	then
		git commit -am "$2"
	else
		git commit -m "$1"
	fi
	git push origin $branch
fi
